
package com.agentefinanciero.Presentation;

import com.agentefinanciero.observer.IObservador;
import javax.swing.JOptionPane;

/**
 * @author Katherin Alexandra Zuñiga Morales
 * @author David Santiago Fernandez Dejoy
 * @author David Santiago Giron Muñoz
 * @author Jeferson Castaño Ossa
 */
public class AgenteFinancieroView extends javax.swing.JFrame implements IObservador {

    /**
     * Creates new form AgenteFinancieroView
     */
    public AgenteFinancieroView() {
        initComponents();
        setLocationRelativeTo(null);
        txtAHistorialNotificaciones.setEditable(false);
        txtAHistorialNotificaciones.setText("Historial de notificaciones:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAgenteFinanciero = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAHistorialNotificaciones = new javax.swing.JTextArea();
        btnLimpiarNotificaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAHistorialNotificaciones.setColumns(20);
        txtAHistorialNotificaciones.setRows(5);
        jScrollPane1.setViewportView(txtAHistorialNotificaciones);

        btnLimpiarNotificaciones.setText("Limpiar");
        btnLimpiarNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarNotificacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgenteFinancieroLayout = new javax.swing.GroupLayout(pnlAgenteFinanciero);
        pnlAgenteFinanciero.setLayout(pnlAgenteFinancieroLayout);
        pnlAgenteFinancieroLayout.setHorizontalGroup(
            pnlAgenteFinancieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgenteFinancieroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlAgenteFinancieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiarNotificaciones)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlAgenteFinancieroLayout.setVerticalGroup(
            pnlAgenteFinancieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgenteFinancieroLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiarNotificaciones)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgenteFinanciero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgenteFinanciero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarNotificacionesActionPerformed
        txtAHistorialNotificaciones.setText("Historial de notificaciones:");
    }//GEN-LAST:event_btnLimpiarNotificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgenteFinancieroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgenteFinancieroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgenteFinancieroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgenteFinancieroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgenteFinancieroView().setVisible(true);
            }
        });
    }

    @Override
    public void actualizar(String mensaje) {
        txtAHistorialNotificaciones.setText(txtAHistorialNotificaciones.getText()+ "\n" + mensaje);
        JOptionPane.showMessageDialog(null, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiarNotificaciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAgenteFinanciero;
    private javax.swing.JTextArea txtAHistorialNotificaciones;
    // End of variables declaration//GEN-END:variables
}
